# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.10"
  - "pypy"
install: pip install coveralls
script: coverage run --source=valideer setup.py test
after_success: coveralls

